Repository aoltra/atenea, pull requests merged in 2023-04, with the labels that each got.

#20 Mejoras en la documentación sobre la colaboración
  doc/how_to_collaborate.md
  doc/tech_tips.md
Labels: documentation

#21 docs: se añade como hacer la verificación del PR
  doc/how_to_collaborate.md
  doc/tech_tips.md
Labels: documentation

#23 Nuevos datos sobre ciclos formativos
  .gitlint
  data/course.xml
  doc/commit_spec.md
  doc/how_to_collaborate.md
  models/school_year.py
  views/views.xml
Labels: data

#36 Feat valid anexos
  misc/pdf/validations/anexo convalidaciones DAM_nochecks.pdf
Labels: enhancement
